type Project {
  id: ID!
  title: String!
  description: String!
  userId: ID!
}

input ProjectInput {
  title: String!
  description: String!
  userId: ID!
}

type Query {
  projects: [Project!]!
  project(id: ID!): Project!
}

type Mutation {
  createProject(data: ProjectInput!): Project!
  updateProject(id: ID!, data: ProjectInput!): Project!
  deleteProject(id: ID): Boolean
}
